version: "3.8"

x-env-vars: &env
  - HOSTNAME: postgres
  - POSTGRES_PASSWORD: postgres
  - POSTGRES_USER: postgres
  - POSTGRES_DB: postgres
  - FLASK_DEBUG: 1

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: pdf_app:1.0
    environment:
      <<: *env
    depends_on:
      - postgres
      - ocr-worker
      - redis
    volumes:
      # files data
      - ./data/original:/data/original/
      - ./data/ocrised:/data/ocrised/
    ports:
      - "5000:5000"
  postgres:
    image: postgres:14.1
    environment:
      <<: *env
    restart: always
    volumes:
      # posgres data
      - ./data/postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      # redis data
      - ./data/redis-data:/data
  ocr-worker:
    build:
      context: .
      dockerfile: docker/ocr-worker/Dockerfile
    image: ocr_worker:1.0
    environment:
      <<: *env
    restart: always
    volumes:
      - ./data/original:/data/original/
      - ./data/ocrised:/data/ocrised/
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
  
volumes:
  postgres-data:

  redis-data: