version: "3.8"

x-env-vars: &env
  - HOSTNAME: postgres
  - POSTGRES_PASSWORD: postgres
  - POSTGRES_USER: postgres
  - POSTGRES_DB: postgres

x-data-volumes: &data-volumes
  - ./data/original:/data/original/
  - ./data/ocrised:/data/ocrised/

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      <<: *env
    depends_on:
      - postgres
      - ocr-worker
      - redis
    volumes:
      - ./data/original:/data/original/
      - ./data/ocrised:/data/ocrised/
    ports:
      - "5000:5000"
  postgres:
    image: postgres:14.1
    environment:
      <<: *env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - redis-data:/data
  ocr-worker:
    # image: geekinutah/python-rq-worker
    build:
      context: .
      dockerfile: docker/ocr-worker/Dockerfile
    environment:
      <<: *env
    depends_on:
      - redis
    restart: always
    volumes:
      - ./data/original:/data/original/
      - ./data/ocrised:/data/ocrised/
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_started
  
volumes:
  postgres-data:

  redis-data: